export const ALL_COUNTRIES = [
    { code: 'AFG', iso2: 'af', label: 'Afghanistan' },
    { code: 'ALB', iso2: 'al', label: 'Albania' },
    { code: 'ALG', iso2: 'dz', label: 'Algeria' },
    { code: 'AND', iso2: 'ad', label: 'Andorra' },
    { code: 'AGO', iso2: 'ao', label: 'Angola' },
    { code: 'ATG', iso2: 'ag', label: 'Antigua and Barbuda' },
    { code: 'ARG', iso2: 'ar', label: 'Argentina' },
    { code: 'ARM', iso2: 'am', label: 'Armenia' },
    { code: 'AUS', iso2: 'au', label: 'Australia' },
    { code: 'AUT', iso2: 'at', label: 'Austria' },
    { code: 'AZE', iso2: 'az', label: 'Azerbaijan' },
    { code: 'BHS', iso2: 'bs', label: 'Bahamas' },
    { code: 'BHR', iso2: 'bh', label: 'Bahrain' },
    { code: 'BGD', iso2: 'bd', label: 'Bangladesh' },
    { code: 'BRB', iso2: 'bb', label: 'Barbados' },
    { code: 'BLR', iso2: 'by', label: 'Belarus' },
    { code: 'BEL', iso2: 'be', label: 'Belgium' },
    { code: 'BLZ', iso2: 'bz', label: 'Belize' },
    { code: 'BEN', iso2: 'bj', label: 'Benin' },
    { code: 'BTN', iso2: 'bt', label: 'Bhutan' },
    { code: 'BOL', iso2: 'bo', label: 'Bolivia' },
    { code: 'BIH', iso2: 'ba', label: 'Bosnia and Herzegovina' },
    { code: 'BWA', iso2: 'bw', label: 'Botswana' },
    { code: 'BRA', iso2: 'br', label: 'Brazil' },
    { code: 'BRN', iso2: 'bn', label: 'Brunei' },
    { code: 'BGR', iso2: 'bg', label: 'Bulgaria' },
    { code: 'BFA', iso2: 'bf', label: 'Burkina Faso' },
    { code: 'BDI', iso2: 'bi', label: 'Burundi' },
    { code: 'CPV', iso2: 'cv', label: 'Cabo Verde' },
    { code: 'KHM', iso2: 'kh', label: 'Cambodia' },
    { code: 'CMR', iso2: 'cm', label: 'Cameroon' },
    { code: 'CAN', iso2: 'ca', label: 'Canada' },
    { code: 'CAF', iso2: 'cf', label: 'Central African Republic' },
    { code: 'TCD', iso2: 'td', label: 'Chad' },
    { code: 'CHL', iso2: 'cl', label: 'Chile' },
    { code: 'CHN', iso2: 'cn', label: 'China' },
    { code: 'COL', iso2: 'co', label: 'Colombia' },
    { code: 'COM', iso2: 'km', label: 'Comoros' },
    { code: 'COG', iso2: 'cg', label: 'Congo' },
    { code: 'COD', iso2: 'cd', label: 'DR Congo' },
    { code: 'CRI', iso2: 'cr', label: 'Costa Rica' },
    { code: 'CIV', iso2: 'ci', label: 'Ivory Coast' },
    { code: 'HRV', iso2: 'hr', label: 'Croatia' },
    { code: 'CUB', iso2: 'cu', label: 'Cuba' },
    { code: 'CYP', iso2: 'cy', label: 'Cyprus' },
    { code: 'CZE', iso2: 'cz', label: 'Czech Republic' },
    { code: 'DNK', iso2: 'dk', label: 'Denmark' },
    { code: 'DJI', iso2: 'dj', label: 'Djibouti' },
    { code: 'DMA', iso2: 'dm', label: 'Dominica' },
    { code: 'DOM', iso2: 'do', label: 'Dominican Republic' },
    { code: 'ECU', iso2: 'ec', label: 'Ecuador' },
    { code: 'EGY', iso2: 'eg', label: 'Egypt' },
    { code: 'SLV', iso2: 'sv', label: 'El Salvador' },
    { code: 'GNQ', iso2: 'gq', label: 'Equatorial Guinea' },
    { code: 'ERI', iso2: 'er', label: 'Eritrea' },
    { code: 'EST', iso2: 'ee', label: 'Estonia' },
    { code: 'SWZ', iso2: 'sz', label: 'Eswatini' },
    { code: 'ETH', iso2: 'et', label: 'Ethiopia' },
    { code: 'FJI', iso2: 'fj', label: 'Fiji' },
    { code: 'FIN', iso2: 'fi', label: 'Finland' },
    { code: 'FRA', iso2: 'fr', label: 'France' },
    { code: 'GAB', iso2: 'ga', label: 'Gabon' },
    { code: 'GMB', iso2: 'gm', label: 'Gambia' },
    { code: 'GEO', iso2: 'ge', label: 'Georgia' },
    { code: 'DEU', iso2: 'de', label: 'Germany' },
    { code: 'GHA', iso2: 'gh', label: 'Ghana' },
    { code: 'GRC', iso2: 'gr', label: 'Greece' },
    { code: 'GRD', iso2: 'gd', label: 'Grenada' },
    { code: 'GTM', iso2: 'gt', label: 'Guatemala' },
    { code: 'GIN', iso2: 'gn', label: 'Guinea' },
    { code: 'GNB', iso2: 'gw', label: 'Guinea-Bissau' },
    { code: 'GUY', iso2: 'gy', label: 'Guyana' },
    { code: 'HTI', iso2: 'ht', label: 'Haiti' },
    { code: 'HND', iso2: 'hn', label: 'Honduras' },
    { code: 'HUN', iso2: 'hu', label: 'Hungary' },
    { code: 'ISL', iso2: 'is', label: 'Iceland' },
    { code: 'IND', iso2: 'in', label: 'India' },
    { code: 'IDN', iso2: 'id', label: 'Indonesia' },
    { code: 'IRN', iso2: 'ir', label: 'Iran' },
    { code: 'IRQ', iso2: 'iq', label: 'Iraq' },
    { code: 'IRL', iso2: 'ie', label: 'Ireland' },
    { code: 'ISR', iso2: 'il', label: 'Israel' },
    { code: 'ITA', iso2: 'it', label: 'Italy' },
    { code: 'JAM', iso2: 'jm', label: 'Jamaica' },
    { code: 'JPN', iso2: 'jp', label: 'Japan' },
    { code: 'JOR', iso2: 'jo', label: 'Jordan' },
    { code: 'KAZ', iso2: 'kz', label: 'Kazakhstan' },
    { code: 'KEN', iso2: 'ke', label: 'Kenya' },
    { code: 'KIR', iso2: 'ki', label: 'Kiribati' },
    { code: 'PRK', iso2: 'kp', label: 'North Korea' },
    { code: 'KOR', iso2: 'kr', label: 'South Korea' },
    { code: 'KWT', iso2: 'kw', label: 'Kuwait' },
    { code: 'KGZ', iso2: 'kg', label: 'Kyrgyzstan' },
    { code: 'LAO', iso2: 'la', label: 'Laos' },
    { code: 'LVA', iso2: 'lv', label: 'Latvia' },
    { code: 'LBN', iso2: 'lb', label: 'Lebanon' },
    { code: 'LSO', iso2: 'ls', label: 'Lesotho' },
    { code: 'LBR', iso2: 'lr', label: 'Liberia' },
    { code: 'LBY', iso2: 'ly', label: 'Libya' },
    { code: 'LIE', iso2: 'li', label: 'Liechtenstein' },
    { code: 'LTU', iso2: 'lt', label: 'Lithuania' },
    { code: 'LUX', iso2: 'lu', label: 'Luxembourg' },
    { code: 'MDG', iso2: 'mg', label: 'Madagascar' },
    { code: 'MWI', iso2: 'mw', label: 'Malawi' },
    { code: 'MYS', iso2: 'my', label: 'Malaysia' },
    { code: 'MDV', iso2: 'mv', label: 'Maldives' },
    { code: 'MLI', iso2: 'ml', label: 'Mali' },
    { code: 'MLT', iso2: 'mt', label: 'Malta' },
    { code: 'MHL', iso2: 'mh', label: 'Marshall Islands' },
    { code: 'MRT', iso2: 'mr', label: 'Mauritania' },
    { code: 'MUS', iso2: 'mu', label: 'Mauritius' },
    { code: 'MEX', iso2: 'mx', label: 'Mexico' },
    { code: 'FSM', iso2: 'fm', label: 'Micronesia' },
    { code: 'MDA', iso2: 'md', label: 'Moldova' },
    { code: 'MCO', iso2: 'mc', label: 'Monaco' },
    { code: 'MNG', iso2: 'mn', label: 'Mongolia' },
    { code: 'MNE', iso2: 'me', label: 'Montenegro' },
    { code: 'MAR', iso2: 'ma', label: 'Morocco' },
    { code: 'MOZ', iso2: 'mz', label: 'Mozambique' },
    { code: 'MMR', iso2: 'mm', label: 'Myanmar' },
    { code: 'NAM', iso2: 'na', label: 'Namibia' },
    { code: 'NRU', iso2: 'nr', label: 'Nauru' },
    { code: 'NPL', iso2: 'np', label: 'Nepal' },
    { code: 'NLD', iso2: 'nl', label: 'Netherlands' },
    { code: 'NZL', iso2: 'nz', label: 'New Zealand' },
    { code: 'NIC', iso2: 'ni', label: 'Nicaragua' },
    { code: 'NER', iso2: 'ne', label: 'Niger' },
    { code: 'NGA', iso2: 'ng', label: 'Nigeria' },
    { code: 'MKD', iso2: 'mk', label: 'North Macedonia' },
    { code: 'NOR', iso2: 'no', label: 'Norway' },
    { code: 'OMN', iso2: 'om', label: 'Oman' },
    { code: 'PAK', iso2: 'pk', label: 'Pakistan' },
    { code: 'PLW', iso2: 'pw', label: 'Palau' },
    { code: 'PSE', iso2: 'ps', label: 'Palestine' },
    { code: 'PAN', iso2: 'pa', label: 'Panama' },
    { code: 'PNG', iso2: 'pg', label: 'Papua New Guinea' },
    { code: 'PRY', iso2: 'py', label: 'Paraguay' },
    { code: 'PER', iso2: 'pe', label: 'Peru' },
    { code: 'PHL', iso2: 'ph', label: 'Philippines' },
    { code: 'POL', iso2: 'pl', label: 'Poland' },
    { code: 'PRT', iso2: 'pt', label: 'Portugal' },
    { code: 'QAT', iso2: 'qa', label: 'Qatar' },
    { code: 'ROU', iso2: 'ro', label: 'Romania' },
    { code: 'RUS', iso2: 'ru', label: 'Russia' },
    { code: 'RWA', iso2: 'rw', label: 'Rwanda' },
    { code: 'KNA', iso2: 'kn', label: 'Saint Kitts and Nevis' },
    { code: 'LCA', iso2: 'lc', label: 'Saint Lucia' },
    { code: 'VCT', iso2: 'vc', label: 'Saint Vincent and the Grenadines' },
    { code: 'WSM', iso2: 'ws', label: 'Samoa' },
    { code: 'SMR', iso2: 'sm', label: 'San Marino' },
    { code: 'STP', iso2: 'st', label: 'Sao Tome and Principe' },
    { code: 'SAU', iso2: 'sa', label: 'Saudi Arabia' },
    { code: 'SEN', iso2: 'sn', label: 'Senegal' },
    { code: 'SRB', iso2: 'rs', label: 'Serbia' },
    { code: 'SYC', iso2: 'sc', label: 'Seychelles' },
    { code: 'SLE', iso2: 'sl', label: 'Sierra Leone' },
    { code: 'SGP', iso2: 'sg', label: 'Singapore' },
    { code: 'SVK', iso2: 'sk', label: 'Slovakia' },
    { code: 'SVN', iso2: 'si', label: 'Slovenia' },
    { code: 'SLB', iso2: 'sb', label: 'Solomon Islands' },
    { code: 'SOM', iso2: 'so', label: 'Somalia' },
    { code: 'ZAF', iso2: 'za', label: 'South Africa' },
    { code: 'SSD', iso2: 'ss', label: 'South Sudan' },
    { code: 'ESP', iso2: 'es', label: 'Spain' },
    { code: 'LKA', iso2: 'lk', label: 'Sri Lanka' },
    { code: 'SDN', iso2: 'sd', label: 'Sudan' },
    { code: 'SUR', iso2: 'sr', label: 'Suriname' },
    { code: 'SWE', iso2: 'se', label: 'Sweden' },
    { code: 'CHE', iso2: 'ch', label: 'Switzerland' },
    { code: 'SYR', iso2: 'sy', label: 'Syria' },
    { code: 'TWN', iso2: 'tw', label: 'Taiwan' },
    { code: 'TJK', iso2: 'tj', label: 'Tajikistan' },
    { code: 'TZA', iso2: 'tz', label: 'Tanzania' },
    { code: 'THA', iso2: 'th', label: 'Thailand' },
    { code: 'TLS', iso2: 'tl', label: 'Timor-Leste' },
    { code: 'TGO', iso2: 'tg', label: 'Togo' },
    { code: 'TON', iso2: 'to', label: 'Tonga' },
    { code: 'TTO', iso2: 'tt', label: 'Trinidad and Tobago' },
    { code: 'TUN', iso2: 'tn', label: 'Tunisia' },
    { code: 'TUR', iso2: 'tr', label: 'Turkey' },
    { code: 'TKM', iso2: 'tm', label: 'Turkmenistan' },
    { code: 'TUV', iso2: 'tv', label: 'Tuvalu' },
    { code: 'UGA', iso2: 'ug', label: 'Uganda' },
    { code: 'UKR', iso2: 'ua', label: 'Ukraine' },
    { code: 'UAE', iso2: 'ae', label: 'UAE' },
    { code: 'GBR', iso2: 'gb', label: 'UK' },
    { code: 'USA', iso2: 'us', label: 'USA' },
    { code: 'URY', iso2: 'uy', label: 'Uruguay' },
    { code: 'UZB', iso2: 'uz', label: 'Uzbekistan' },
    { code: 'VUT', iso2: 'vu', label: 'Vanuatu' },
    { code: 'VAT', iso2: 'va', label: 'Vatican City' },
    { code: 'VEN', iso2: 've', label: 'Venezuela' },
    { code: 'VNM', iso2: 'vn', label: 'Vietnam' },
    { code: 'YEM', iso2: 'ye', label: 'Yemen' },
    { code: 'ZMB', iso2: 'zm', label: 'Zambia' },
    { code: 'ZWE', iso2: 'zw', label: 'Zimbabwe' }
];
